name: SIRVAL API Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman (Postman CLI)
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run API Tests
      env:
        NGROK_URL: ${{ secrets.NGROK_URL }}  # Configúralo en GitHub Secrets
      run: |
        newman run ./postman/sirval-collection.json \
          --environment ./postman/sirval-environment.json \
          --global-var "base_url=$NGROK_URL" \
          --reporters htmlextra \
          --reporter-htmlextra-export ./test-results/report.html

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: sirval-test-report
        path: ./test-results/report.html
