name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: |
          newman run postman/SIRVAL.postman_collection.json \
            -e postman/SIRVAL.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: report.html
